package day08

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import se.horv.day08.Day08

class Day08Test {
    @Test
    fun part1() {
        val result = Day08().solve("""............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""".split("\n"), false)

        assertEquals("14", result)
    }

    @Test
    fun part2() {
        val result = Day08().solve("""............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............""".split("\n"), true)

        assertEquals("34", result)
    }
}